name: Django Test

on:
  workflow_call:
  workflow_dispatch:
  push:
      branches: [main]
  pull_request:
      branches: [main]
jobs:
  simple_build_django:
    runs-on: ubuntu-latest
    env:
      PSQL_USERNAME: francisco_luna
      PSQL_PASS: 123World000%
      PSQL_DBNAME: francisco_lunadb
      PSQL_HOST: localhost # default host value for the database
      PSQL_PORT: 5432
      JWT_TOKEN_TIME: "120"
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{env.PSQL_USERNAME}}
          POSTGRES_PASSWORD: ${{env.PSQL_PASS}}
          POSTGRES_DB: ${{env.PSQL_DBNAME}}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10.4
        uses: actions/setup-python@v2
        with:
           python-version: 3.10.4
      - name: Install requirements
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Make migrations
        run: python manage.py makemigrations
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: pytest